### ISSUE TITLE
Test and ensure we recover from crashes

### ISSUE THREAD

**Issue by treeman** [bitpal/bitpal#4]
No matter what part crashes, we need to ensure that we can recover.

Write tests for (at least) these cases:

- [x] `InvoiceHandler` crashes
- [ ] The backend process crashes
- [ ] The node connection closes/crashes
- [ ] The external node process (the Flowee process on the OS level) shuts down/restarts
- [ ] The whole `BitPal` process crashes

For this to work we need to persist invoices to db, and upon restart we need to recheck the status.

**Comment by treeman** [comment]
Notes from another issue:

- When an InvoiceHandler inits, if status isn't draft, then we need to recover the previous state
- What happens when Flowee connection fails?
- What if our Flowee process restarts? Then we need to reset address watchers.

**Comment by treeman** [comment]
@fstromback this is what I think our Flowee process needs to do at startup:

- Get a list of all open invoices, and gather all transaction outputs to the matching addresses
- Make sure they're all confirmed and make sure to recheck the affected invoices (if they're paid or not)

We can compare the block height of Flowee with the last registered block height if we want to, but maybe it's more robust to recheck it all anyway, as tx messages are separate from new block messages?

So Flowee just needs to be able to answer "get all txs to these addresses".

**Comment by treeman** [comment]
Right now in `start_hub` we do this:

    Enum.each(Invoices.open_addresses(@bch), fn address ->
      subscribe_addr(c, address)
    end)

So here we can just retrieve all txs to these addresses, and mark them as seen/double spent/confirmed.

**Comment by fstromback** [comment]
I more or less agree.

The downside with this approach is that it requires the separate Indexer process. This requires its own database which takes up several hundred GBs in addition to what Flowee requires out of the box. It also takes a considerable amount of time to build this database (I never had the patience to let mine finish, even though I did use a sqlite database which is not ideal).

Since we know approximately where the transactions we are looking for are in the blockchain (we know at what block we generated the address, possibly also when it was accepted into a block), I think it is a better approach to just examine the relevant blocks at the end of the blockchain. I think we can still let Flowee filter the data in the blocks for us, so that we only get the transactions we are interested in to the Elixir process. By giving Flowee this "hint" of where we are looking, we save quite a lot of disk space for our users.

**Comment by treeman** [comment]
> I think we can still let Flowee filter the data in the blocks for us, so that we only get the transactions we are interested in to the Elixir process. By giving Flowee this "hint" of where we are looking, we save quite a lot of disk space for our users.

Hmm, alright. It would be nice to save that amount of space. If Flowee can filter them then it's basically the same in practice I guess?

**Comment by fstromback** [comment]
Yes, I think so. It depends a bit on exactly what Flowee can filter for us etc, but I will investigate and come back on that note. It is the next thing on my agenda to do anyway (as I mentioned in pull request #50)
