### ISSUE TITLE
Generate a new address for each payment request

### ISSUE THREAD

**Issue by treeman** [bitpal/bitpal#9]
Instead of reusing the same address, we should generate a new one from a public key.

We might still keep this behavior to simplify usage? But it shouldn't be recommended.

**Comment by treeman** [comment]
See here for some considerations of derivation paths: https://github.com/Bitcoin-com/Wallet/issues/507

**Comment by fstromback** [comment]
It seems we need Base58 encoding/decoding for proper support here, we probably also need to be able to generate bitcoincash: links (currently, we only decode them).

I have basic logic for elliptic curves that seems to be working decently at least, so this looks doable at the moment.

**Comment by treeman** [comment]
Base58 seems fairly easy, and a quick google produces these:

http://www.petecorey.com/blog/2018/01/08/bitcoins-base58check-in-pure-elixir/
https://github.com/jrdnull/base58
https://github.com/dougal/base58.ex

If we can find well maintained existing libraries for cryptography things, I'd vastly prefer that instead of rolling our own.

**Comment by treeman** [comment]
I don't know what kind of ecc you're looking for, but there is an existing ecc library for elixir here: https://github.com/farao/elixir-ecc

**Comment by fstromback** [comment]
Base 58 should indeed not be problematic, it is "only" base32 with some extra steps I think. I will make something similar to the Base32 code already in there (it has checksum support, etc. as well, it is nice to not have to think about that outside the encoding).

I found the elixir-ecc before, it seems to be a fairly thin wrapper over openssl (38 + 55 lines of code), with the aim of signing and verifying signatures and the like. Sadly, this is not enough for deriving keys etc. For that, I need to perform group operations on the curve itself. These are fairly well described in the articles mentioned in the BIP:s above (particularly this one: http://www.secg.org/sec1-v2.pdf), and using the big integers in Elixir, they are not that tricky to implement (see https://github.com/fstromback/bitpal/commit/778615048b371e5f2d6b0de869face38433ec3e5 for my current sketch, it is around 150 lines of code, and I think I don't need much more except possibly support for "compressed points" (btw: the "diophantine" function is from our adventures in competetive programming)).

I agree that it would be nice to use an established library for these kind of operations (and I definitely would for anything more high-level, like SSL, certificates, etc.). As this basic ECC functionality is fairly simple and the "primitives" for doing the crypto-specific key derivation steps (which we will have to implement anyway), I think it is better to have our own implementation (that we know doesn't do anything) rather than depending on a library that may or may not be maintained (the one you linked was last updated more than a year ago it seems). The best long-term option here would probably be to use the ECC implementation in OpenSSL (I have not looked at it, but based on prior experience I am fairly sure that it exposes sufficient details to be usable in this context). It will be easy to replace the current ECC implementation with one that calls OpenSSL (or any other we find), but as I have no idea how to call "native" code at the moment, this is a decent start (especially as I now have some kind of feel for what the key derivation stuff is actually doing).

The potential issue with this kind of implementation is, of course, side-channel attacks that could reveal parts of some "secret". In our particular use-case, it is not too much of an issue since we 1: only operate on public keys (if data is leaked, it will at the very least not allow anyone to spend coins) and 2: if we generate public addresses ahead of time, it would require the attacker to ask for many keys in a quick succession to force generation of new keys. If we always do this in batches, I think it would be difficult to reclaim much, if any, of the secrets.

**Comment by treeman** [comment]
Then maybe we should use the Erlang crypto library: https://erlang.org/doc/man/crypto.html ?

You can interface directly with any Erlang library via atoms, for example:

```
:crypto.hash(:sha256, "abc") |> :crypto.bytes_to_integer
```

This is probably the ECC we want to use for example:

```
iex(6)> :crypto.ec_curve(:secp256k1)
{{:prime_field,
  <<255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
    255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 254, 255, 255,
    252, 47>>}, {<<0>>, "\a", :none},
 <<4, 121, 190, 102, 126, 249, 220, 187, 172, 85, 160, 98, 149, 206, 135, 11, 7,
   2, 155, 252, 219, 45, 206, 40, 217, 89, 242, 129, 91, 22, 248, 23, 152, 72,
   58, 218, 119, 38, 163, 196, 101, 93, 164, 251, 252, 14, 17, ...>>,
 <<255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
   254, 186, 174, 220, 230, 175, 72, 160, 59, 191, 210, 94, 140, 208, 54, 65,
   65>>, <<1>>}
```

**Comment by fstromback** [comment]
Yes, it seems to be the same curve. From what I can see, the Erlang crypto library has the same problem as the others: I don't find "low-level" operations, only higher level operations such as "sign", "encrypt", etc. I think would need something like the EC_POINT family of functions in OpenSSL: https://www.openssl.org/docs/man1.0.2/man3/ec.html

**Comment by fstromback** [comment]
I think a decent way forward is to keep the EC stuff and the key derivation stuff modularized, then get it to work with the current implementation. At that point it will be very clear what is needed, and we can swap it for OpenSSL, or whatever is suitable at that point (maybe using native code in Rust or something like that if there is nothing more suitable).

**Comment by treeman** [comment]
Alright, a new attempt then!

I haven't looked into the source that much, but doesn't this repo do what we want https://github.com/KamilLelonek/ex_wallet ? See Extended.Children in the readme. It also has a bunch of articles explaining what it does (haven't read them yet though.)

It seems to use this lib: https://github.com/exthereum/libsecp256k1

So I still don't think it's a good use of our time to re-implement EC.

**Comment by fstromback** [comment]
Looks promising. I'll see if I get it to work (the red CI badge on libsecp256k1 is a bit worrying). Did you find a license for the ex_wallet library? I can't seem to find anything at all there.

**Comment by treeman** [comment]
Yeah I can't find a license either, so best not to look at the wallet code.

Hopefully the libsecp256k1 lib works out. Otherwise integrating a rust library [like this](https://github.com/RustCrypto/elliptic-curves) is the best solution.

**Comment by treeman** [comment]
Oh and if we do go the rust route, rustler seems like a very good interface library: https://github.com/rusterlium/rustler

**Comment by fstromback** [comment]
Sounds like a plan. I'll do my best to get the libsecp256k1 to work (the red CI mark is a bit worrying, hopfully it is just due to some configuration being stale). It seems to be an Erlang wrapper over a C library intended for Bitcoin with the same name, so that is promising. The rest of the steps I think were quite well described in  BIP-0032 as well, so I have a good general idea of what needs to be done. With that one, and the article you pointed at, I can probably get it working without too much hassle.

**Comment by fstromback** [comment]
It seems to build (at least on Linux), but I get these warnings which are a bit worrying:

```
cc -I/usr/lib/erlang/erts-11.1.3/include -I c_src/secp256k1 -I c_src/secp256k1/src -I c_src/secp256k1/include -I../libsecp256k1/src -fPIC -shared -o priv/libsecp256k1_nif.so c_src/libsecp256k1_nif.c c_src/secp256k1/.libs/libsecp256k1.a -lgmp
c_src/libsecp256k1_nif.c: In function ‘ecdsa_sign’:
c_src/libsecp256k1_nif.c:494:51: warning: passing argument 2 of ‘secp256k1_ecdsa_signature_serialize_der’ from incompatible pointer type [-Wincompatible-pointer-types]
  494 |  if (secp256k1_ecdsa_signature_serialize_der(ctx, &intermediatesig, &siglen, &signature) != 1) {
      |                                                   ^~~~~~~~~~~~~~~~
      |                                                   |
      |                                                   unsigned char (*)[74]
In file included from c_src/libsecp256k1_nif.c:9:
c_src/secp256k1/src/secp256k1.c:261:90: note: expected ‘unsigned char *’ but argument is of type ‘unsigned char (*)[74]’
  261 | 56k1_ecdsa_signature_serialize_der(const secp256k1_context* ctx, unsigned char *output, size_t *outputlen, const secp256k1_ecdsa_signature* sig) {
      |                                                                  ~~~~~~~~~~~~~~~^~~~~~

In file included from c_src/secp256k1/src/secp256k1.c:9,
                 from c_src/libsecp256k1_nif.c:9:
c_src/libsecp256k1_nif.c:497:64: warning: passing argument 3 of ‘secp256k1_ecdsa_signature_parse_der’ from incompatible pointer type [-Wincompatible-pointer-types]
  497 |     CHECK(secp256k1_ecdsa_signature_parse_der(ctx, &signature, &intermediatesig, siglen) == 1);
      |                                                                ^~~~~~~~~~~~~~~~
      |                                                                |
      |                                                                unsigned char (*)[74]
c_src/secp256k1/src/util.h:40:39: note: in definition of macro ‘EXPECT’
   40 | #define EXPECT(x,c) __builtin_expect((x),(c))
      |                                       ^
c_src/libsecp256k1_nif.c:497:5: note: in expansion of macro ‘CHECK’
  497 |     CHECK(secp256k1_ecdsa_signature_parse_der(ctx, &signature, &intermediatesig, siglen) == 1);
      |     ^~~~~
In file included from c_src/libsecp256k1_nif.c:9:
c_src/secp256k1/src/secp256k1.c:224:124: note: expected ‘const unsigned char *’ but argument is of type ‘unsigned char (*)[74]’
  224 | st secp256k1_context* ctx, secp256k1_ecdsa_signature* sig, const unsigned char *input, size_t inputlen) {
      |                                                            ~~~~~~~~~~~~~~~~~~~~~^~~~~

```

I checked, and it *should* not be a problem (seems like &signature and signature give the same address, but different type). Also, I don't think we need this particular function (it is in ecdsa_sign), but worth noting.

**Comment by treeman** [comment]
Cool. I think it's fine, and if we find a better library we can just switch later on.

**Comment by fstromback** [comment]
I *think* I have managed to implement BIP-0032 fairly well now. It agrees with all the test cases in BIP-0032 at least, and a few other things I tried. It is in the branch key-tree in my fork if you want to have a look.

I have not yet figured out exactly how to integrate this with bitcoincash: addresses. I got a master public key from my wallet and saw that it was on level 3, so I assume it is the "root" key for the wallets there. But when I derive key number 0 from there, it does not agree with the wallet. I'm probably missing a level of the key derivation path somewhere. Anyway, that's why I have not merged the implementation to my master yet, I want to test it a bit more first.

**Comment by treeman** [comment]
You can check legacy addresses in Electron Cash as well, so it displays them instead of bitcoincash: addresses, if there's something wrong with our conversion there.

**Comment by treeman** [comment]
With key derivation, it shouldn't be too hard to add use an unique address per payment. I've begun moving towards that by persisting stuff to database (and some refactoring) here: https://github.com/bitpal/bitpal/pull/36

**Comment by fstromback** [comment]
Great!

I just remembered one thing that is important to keep in mind (it is documented, but as it is not obvious it is worth pointing out again): There is a small chance that key derivation at any stage fails (due to how the crypto works, not due to a bug in the implementation). So, when generating the sequence of wallets, if one of them fails, the correct thing to do is to just skip that and go to the next one. Since we potentially generate many of these wallets, we should keep this in mind so that the system manages to skip over these few invalid indices. The probability is about 1 in 2^128 if I remember correctly, so it won't happen often (and thus difficult to test).
